apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityserver-deployment
  labels:
    app: identityserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identityserver
  template:
    metadata:
      labels:
        app: identityserver
    spec:
      containers:
        - name: identityserver
          image: identityserveracr.azurecr.io/identityserver:v1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80          
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: identityserver-service
spec:  
  selector:
    app: identityserver
  ports:
    - protocol: TCP
      port: 80